### ISSUE TITLE
Remove unnecessary import

### ISSUE THREAD

**Issue by mcmathmo** [40wa/NumberBrain#1]
https://github.com/40wa/NumberBrain/blob/3e438a7ad32e13502c88adddd6d5e1d4dd19ba0a/src/main.py#L1

Don't import os

**Comment by 40wa** [comment]
> https://github.com/40wa/NumberBrain/blob/3e438a7ad32e13502c88adddd6d5e1d4dd19ba0a/src/main.py#L1
> 
> Don't import os

os has been removed. Closing issue.

**Comment by 40wa** [comment]
Alright, mb.
